# Generated by Django 5.2.7 on 2025-10-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('raw_text', models.TextField()),
                ('plain_text', models.TextField()),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
