services:
  scrapper_web:
    build: .
    container_name: scrapper_container
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - pg_db

  pg_db:
    image: postgres:18-alpine3.22
    container_name: pg_container
    restart: always
    environment:
      POSTGRES_DB: articles_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: passwd123
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg_data:
